### ISSUE TITLE
Link to make profile changes not found

### ISSUE THREAD

**Issue by Framinus** [LearnersGuild/idm#206]
When I click on my profile picture in the top right corner of the page and select "my profile" here:
<img width="1136" alt="echo-user-page" src="https://user-images.githubusercontent.com/24632499/30182046-49902a32-93ca-11e7-8280-3da9cfb8ce59.png">

 the link sends me to a page that doesn't exist: 

<img width="456" alt="echo idm" src="https://user-images.githubusercontent.com/24632499/30181921-d3a59726-93c9-11e7-8bdb-35a4df5d807e.png">

**Comment by prattsj** [comment]
@Framinus: Thanks for reporting! Should be resolved. Can you check to see if you're still having this issue?

**Comment by Framinus** [comment]
I tried again, and this time I'm getting a 500 status code - Internal Server Error. Tried it a few times, same result.

**Comment by prattsj** [comment]
Got it, thanks. I think it might've uncovered a separate bug. Will investigate and follow-up.

**Comment by prattsj** [comment]
Likely related: https://github.com/LearnersGuild/idm/issues/212

**Comment by prattsj** [comment]
@Framinus: should be fixed.
