### ISSUE TITLE
Cannot update profile photo.

### ISSUE THREAD

**Issue by diop** [LearnersGuild/idm#216]
* Navigate to idm.learnersguild.org
* Click on Profile link
* Click on edit photo
* Drag and Drop image 
* Click on Save
* Encountering an error. 
![screen shot 2017-09-25 at 1 53 45 pm](https://user-images.githubusercontent.com/971941/30830624-72abfd1e-a1f9-11e7-83c1-e90bfc5ada74.png)

**Comment by prattsj** [comment]
Fixed in https://github.com/LearnersGuild/idm/commit/41b5b3f29b1f37976a845babcc50254d51e0f0ec.
